{% set name = "percy" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda-distribution/percy/archive/refs/tags/{{ version }}.tar.gz
  sha256: d43e3b66628994f92bdb6eafc5b107f1b0d70ea42ce92cb8693202f260ba36f8

build:
  number: 0 # trigger
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - percy = percy.commands.main:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - click
    - conda
    - jinja2
    - pyyaml
    - requests

test:
  imports:
    - percy.render.recipe
    - percy.render.aggregate
    - percy.repodata.repodata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anaconda-distribution/percy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://github.com/anaconda-distribution/percy
  dev_url: https://github.com/anaconda-distribution/percy