{% set name = "percy" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda-distribution/percy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 605f32c789328546527fcc7c70d523acea67c729c1dac8b1077141aa9223ba53

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - percy = percy.commands.main:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - click >=8.1.6
    - conda
    - jinja2
    - pyyaml
    - requests
    - jsonschema

test:
  imports:
    - percy.render.recipe
    - percy.render.aggregate
    - percy.repodata.repodata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anaconda-distribution/percy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://github.com/anaconda-distribution/percy
  dev_url: https://github.com/anaconda-distribution/percy