{% set name = "percy" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda-distribution/percy/archive/refs/tags/{{ version }}.tar.gz
  sha256: b3fec5efdeec94effac721e7c00d7f96c4f4a2131319121e6d750fed0a8f9fd8

build:
  number: 0
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - percy = percy.commands.main:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - click
    - conda
    - jinja2
    - pyyaml
    - requests
    - jsonschema

test:
  imports:
    - percy.render.recipe
    - percy.render.aggregate
    - percy.repodata.repodata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/anaconda-distribution/percy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://github.com/anaconda-distribution/percy
  dev_url: https://github.com/anaconda-distribution/percy