{% set name = "percy" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda-distribution/percy/archive/refs/tags/{{ version }}.tar.gz
  sha256: f2d6d906095d52a79d9c47b3b6699fc7f66e36629f449518175128765871287c

build:
  number: 1
  noarch: python
  script: pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - percy = percy.commands.main:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.11
    - click >=8.1.7
    - conda
    - jinja2
    - pyyaml
    - requests
    - jsonschema

test:
  imports:
    - percy.render.recipe
    - percy.render.aggregate
    - percy.repodata.repodata
  requires:
    - pip
  commands:
    - pip check
    - python -m pytest -n auto --capture=no percy/tests/

about:
  home: https://github.com/anaconda-distribution/percy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Helper tool for recipes on aggregate.
  description: |
    Renders local recipes, provides build orders, find outdated recipes.
  doc_url: https://github.com/anaconda-distribution/percy
  dev_url: https://github.com/anaconda-distribution/percy